# Generated by Django 5.0.1 on 2024-02-03 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('img_brend', models.ImageField(upload_to='\\static\\imgmod')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sport_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='\\static\\imgmod')),
                ('brend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysport.brend')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysport.sport_item')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysport.sport_item')),
            ],
        ),
        migrations.CreateModel(
            name='Characheristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.CharField(max_length=5)),
                ('country_crator', models.CharField(max_length=25)),
                ('vid_sport', models.CharField(max_length=20)),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysport.sport_item')),
            ],
        ),
        migrations.CreateModel(
            name='Subcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysport.category')),
            ],
        ),
        migrations.CreateModel(
            name='Subcat_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('img_subcatcat', models.ImageField(upload_to='\\static\\imgmod')),
                ('subcutscats', models.ManyToManyField(to='mysport.sport_item')),
            ],
        ),
    ]
