# Generated by Django 5.0.1 on 2024-02-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='img_brend',
            field=models.ImageField(upload_to='D:\\projects4IP\\Django_Kursovaya-main\\sporttovars\\static\\imgmod'),
        ),
        migrations.AlterField(
            model_name='sport_item',
            name='img',
            field=models.ImageField(upload_to='D:\\projects4IP\\Django_Kursovaya-main\\sporttovars\\static\\imgmod'),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='img_subcatcat',
            field=models.ImageField(null=True, upload_to='D:\\projects4IP\\Django_Kursovaya-main\\sporttovars\\static\\imgmod'),
        ),
    ]
