# Generated by Django 5.0.1 on 2024-02-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0002_alter_subcat_subcutscats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
