# Generated by Django 5.0.1 on 2024-02-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0002_alter_brend_img_brend_alter_sport_item_img_and_more'),
        ('mysport', '0002_alter_subcat_subcutscats'),
    ]

    operations = [
    ]
