# Generated by Django 5.0.1 on 2024-03-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0002_anonymcustomer_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymcustomer',
            name='city',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=35),
        ),
    ]
