# Generated by Django 5.0.1 on 2024-02-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0002_alter_brend_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcat_cat',
            name='subcat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysport.subcat'),
        ),
    ]
