# Generated by Django 5.0.1 on 2024-02-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0003_subcat_cat_subcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport_item',
            name='brend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysport.brend'),
        ),
    ]
