# Generated by Django 5.0.1 on 2024-02-08 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0003_alter_size_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='characheristic',
            name='material',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characheristic',
            name='season_year',
            field=models.CharField(max_length=15),
        ),
    ]
