# Generated by Django 5.0.1 on 2024-02-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0004_characheristic_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characheristic',
            name='material',
            field=models.CharField(max_length=50),
        ),
    ]
