# Generated by Django 5.0.1 on 2024-02-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0004_alter_sport_item_brend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcat_cat',
            name='subcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysport.subcat'),
        ),
    ]
