# Generated by Django 5.0.1 on 2024-05-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0004_order_anonymuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_moder',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
