# Generated by Django 5.0.1 on 2024-05-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0005_user_is_moder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deny_buy',
            field=models.BooleanField(default=False),
        ),
    ]
