# Generated by Django 5.0.1 on 2024-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0005_alter_characheristic_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characheristic',
            name='material',
            field=models.CharField(max_length=30),
        ),
    ]
