# Generated by Django 5.0.1 on 2024-02-11 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0007_alter_characheristic_vid_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='good',
        ),
        migrations.RemoveField(
            model_name='size',
            name='good',
        ),
        migrations.AddField(
            model_name='sport_item',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysport.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport_item',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysport.size'),
            preserve_default=False,
        ),
    ]
