# Generated by Django 5.0.1 on 2024-05-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0008_alter_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_moder',
            field=models.BooleanField(default=False),
        ),
    ]
