# Generated by Django 5.0.1 on 2024-02-11 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0008_remove_color_good_remove_size_good_sport_item_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport_item',
            name='size',
        ),
        migrations.AddField(
            model_name='size',
            name='good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysport.sport_item'),
            preserve_default=False,
        ),
    ]
