# Generated by Django 5.0.1 on 2024-02-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0003_merge_20240208_1103'),
        ('mysport', '0009_remove_sport_item_size_size_good'),
    ]

    operations = [
    ]
