# Generated by Django 5.0.1 on 2024-02-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0010_merge_20240216_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='img_brend',
            field=models.ImageField(upload_to='D:\\projects\\kursov_futurediplom\\sporttovars\\static\\imgmod'),
        ),
    ]
