# Generated by Django 5.0.1 on 2024-02-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0011_alter_brend_img_brend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='img_brend',
            field=models.ImageField(upload_to='D:\\projects4IP\\Django_Kursovaya-main\\sporttovars\\static\\imgmod'),
        ),
    ]
