# Generated by Django 5.0.1 on 2024-03-09 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0012_alter_brend_img_brend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='img_brend',
            field=models.ImageField(upload_to='D:\\projects\\kursov_futurediplom\\sporttovars\\static\\imgmod'),
        ),
        migrations.AlterField(
            model_name='sport_item',
            name='img',
            field=models.ImageField(upload_to='D:\\projects\\kursov_futurediplom\\sporttovars\\static\\imgmod'),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='img_subcatcat',
            field=models.ImageField(null=True, upload_to='D:\\projects\\kursov_futurediplom\\sporttovars\\static\\imgmod'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('postal_index', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
