# Generated by Django 5.0.1 on 2024-03-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysport', '0014_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
